export const API_ROUTES = {
  signUp: "/api/sign-up",
  signIn: "/api/sign-in",
  forgotPassword: "/api/forgot-password",
  resetPassword: "/api/reset-password",
  profile: "/api/profile",
  farms: "/api/farms",
  farm: (id: string) => `/api/farms/${id}`,
  listings: "/api/listings",
  listing: (id: string) => `/api/listings/${id}`,
  listingStatus: (id: string) => `/api/listings/${id}/status`,
  priceRecommendation: "/api/ai/price-recommendation",
  buyerMatches: "/api/ai/buyer-matches",
  learningEntries: "/api/ai/learning",
  learningEntry: (id: string) => `/api/ai/learning/${id}`,
} as const
