import type { District } from "@prisma/client"

export const DISTRICTS: { value: District; label: string }[] = [
  { value: "GASABO", label: "Gasabo" },
  { value: "KICUKIRO", label: "Kicukiro" },
  { value: "NYARUGENGE", label: "Nyarugenge" },
  { value: "BURERA", label: "Burera" },
  { value: "GAKENKE", label: "Gakenke" },
  { value: "GICUMBI", label: "Gicumbi" },
  { value: "MUSANZE", label: "Musanze" },
  { value: "RULINDO", label: "Rulindo" },
  { value: "GISAGARA", label: "Gisagara" },
  { value: "HUYE", label: "Huye" },
  { value: "KAMONYI", label: "Kamonyi" },
  { value: "MUHANGA", label: "Muhanga" },
  { value: "NYAMAGABE", label: "Nyamagabe" },
  { value: "NYANZA", label: "Nyanza" },
  { value: "NYARUGURU", label: "Nyaruguru" },
  { value: "RUHANGO", label: "Ruhango" },
  { value: "BUGESERA", label: "Bugesera" },
  { value: "GATSIBO", label: "Gatsibo" },
  { value: "KAYONZA", label: "Kayonza" },
  { value: "KIREHE", label: "Kirehe" },
  { value: "NGOMA", label: "Ngoma" },
  { value: "NYAGATARE", label: "Nyagatare" },
  { value: "RWAMAGANA", label: "Rwamagana" },
  { value: "KARONGI", label: "Karongi" },
  { value: "NGORORERO", label: "Ngororero" },
  { value: "NYABIHU", label: "Nyabihu" },
  { value: "NYAMASHEKE", label: "Nyamasheke" },
  { value: "RUBAVU", label: "Rubavu" },
  { value: "RUSIZI", label: "Rusizi" },
  { value: "RUTSIRO", label: "Rutsiro" },
]
