export const ROUTES = {
  home: "/",
  listings: "/listings",
  listing: (id: string) => `/listings/${id}`,
  dashboard: "/dashboard",
  dashboardFarms: "/dashboard/farms",
  dashboardFarm: (id: string) => `/dashboard/farms/${id}`,
  dashboardProduces: "/dashboard/produces",
  dashboardNewProduce: "/dashboard/produces/new",
  dashboardProduce: (id: string) => `/dashboard/produces/${id}`,
  dashboardEditProduce: (id: string) => `/dashboard/produces/${id}/edit`,
  dashboardLearning: "/dashboard/learning",
  dashboardBuyers: "/dashboard/buyers",
  dashboardProfile: "/dashboard/profile",
  signIn: "/auth/sign-in",
  signUp: "/auth/sign-up",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
} as const
